# Generated by Django 4.2.7 on 2023-11-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('user_surname', models.CharField(max_length=30)),
                ('user_e_mail', models.EmailField(max_length=50)),
                ('user_password', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
