# Generated by Django 4.2.7 on 2023-11-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=500)),
                ('item_date_added', models.DateTimeField(auto_now_add=True)),
                ('item_image', models.ImageField(upload_to='uploaded_images/')),
                ('item_price', models.FloatField()),
            ],
        ),
    ]
